- hosts:  admins
  tags:
       - boostrap_cluster
  become: "{{ root_user }}"
  tasks:
       - name: Perform a Registry Login on the bootstrap node
         cephadm_registry_login:
             state: login
             registry_url: "{{ registry_url }}"
             registry_username: "{{ registry_username }}"
             registry_password: "{{ registry_pass }}"
         when: use_registry_auth | bool


       - name: Check the node is already bootstrapped or not
         ansible.builtin.shell:
                 cmd: netstat -tnlp | grep 3300 | wc -l
         register: bootstrap_status


       - name: Print Output
         ansible.builtin.debug:
                 msg: "{{ bootstrap_status.stdout | int }}"


       - name: Boostrap the cluster
         cephadm_bootstrap:
             mon_ip: "{{ ansible_facts['all_ipv4_addresses'] | ansible.utils.ipaddr('10.74.253.45/21') | join() }}"
             image: "{{ cluster_image }}"
             monitoring: "{{ use_monitoring }}"
             cluster_network: "{{ cluster_network }}"
         when: ( bootstrap_status.stdout | int < 1 )

- hosts: cluster_a
  become: True
  tags:
      - add_hosts
  tasks:
  - block:
      - name: Add Hosts into the cluster
        ceph_orch_host:
                name: "{{ ansible_facts['hostname'] }}"
                address: "{{ ansible_facts['all_ipv4_addresses'] | ansible.utils.ipaddr('10.74.253.45/21') | join() }}"
                labels: "{{ labels }}"
                state: present
    when: hostvars[inventory_hostname]['role'] is defined and hostvars[inventory_hostname]['role'] != "drain" 


- hosts: cluster_a
  become: True
  tags:
      - remove_hosts
  tasks:
  - block:
      - name: Drain the node
        ceph_orch_host:
                name: "{{ ansible_facts['hostname'] }}"
                state: drain

      - name: Remove Hosts into the cluster
        ceph_orch_host:
                name: "{{ ansible_facts['hostname'] }}"
                address: "{{ ansible_facts['all_ipv4_addresses'] | ansible.utils.ipaddr('10.74.253.45/21') | join() }}"
                labels: "{{ labels }}"
                state: present

      - name: List the hosts associated with the cluster
        ansible.builtin.shell:
                cmd: ceph orch host ls
        register: out

      - name: Print the host list
        ansible.builtin.debug:
                msg: "{{ out.stdout }}"


    when: hostvars[inventory_hostname]['role'] == "drain"

- hosts: admins
  become: true
  tasks:
      - name: Deploy all the service spec file
        ceph_orch_apply:
                spec: "{{ initial_sepc }} "


                       
