- hosts: localhost
  gather_facts: false
  tasks:
     - name: Set the variable cluster_env if not defined
       ansible.builtin.set_fact:
             cluster_env : 'all'
             admin_hostname: "admin"
       when: cluster_env is undefined

     - name: Setting hostvar for where to run the Host addition play
       ansible.builtin.set_fact:
          admin_hostname: "{{ item }}"
       when: ( hostvars[item].cluster_group_name == cluster_env )
       loop: "{{ groups['admin'] }}"


- hosts: "{{ hostvars['localhost'].admin_hostname }}" 
  tags:
       - boostrap_cluster
       - deploy_service
  become: "{{ root_user }}"
  #serial: 1
  tasks:
       - name: Perform a Registry Login on the bootstrap node
         cephadm_registry_login:
             state: login
             registry_url: "{{ registry_url }}"
             registry_username: "{{ registry_username }}"
             registry_password: "{{ registry_pass }}"
         when: use_registry_auth | bool


       - name: Check the node is already bootstrapped or not
         ansible.builtin.shell:
                 cmd: netstat -tnlp | grep 3300 | wc -l
         register: bootstrap_status


       - name: Print Output
         ansible.builtin.debug:
                 msg: "{{ bootstrap_status.stdout | int }}"


       - name: Boostrap the cluster
         cephadm_bootstrap:
             mon_ip: "{{ ansible_facts['all_ipv4_addresses'] | ansible.utils.ipaddr('10.74.253.45/21') | join() }}"
             image: "{{ cluster_image }}"
             monitoring: "{{ use_monitoring }}"
             cluster_network: "{{ cluster_network }}"
         when: ( bootstrap_status.stdout | int < 1 )


- name: Adding Hosts and deploying the SSH Keys
  hosts: "{{ hostvars['localhost'].admin_hostname }}"
  become: True
  tags:
      - add_hosts
      - deploy_service
  gather_facts: true
  #serial: 1
  tasks:
      - name: Deploy SSH Keys on the hosts
        ansible.builtin.shell:
                cmd: "ansible-playbook -i {{ groups[hostvars[inventory_hostname].cluster_group_name] | join(',') }} cephadm-distribute-ssh-key.yml -e cephadm_ssh_user={{ cepadm_ssh_user }} -e admin_node={{ inventory_hostname }} -vv"
        async: 100
        poll: 5
        #run_once: true
        changed_when: false
        delegate_to: localhost

      - name: Add Hosts into the cluster
        ceph_orch_host:
                name: "{{ item.name }}"
                address: "{{ item.address  }}"
                labels: "{{ item.labels }}"
                state: present
        loop: "{{ host_list }}"
        #delegate_to: inventorydd
        #run_once: true

- hosts: "{{ hostvars['localhost'].admin_hostname }}"
  become: true
  tags:
          - deploy_service
  tasks:
      - name: Deploy all the service spec file
        ceph_orch_apply:
                spec: "{{ initial_spec }} "


                       
