- hosts: localhost
  gather_facts: false
  tasks:
     - name: Set the variable cluster_env if not defined
       ansible.builtin.set_fact:
              cluster_env: 'all'
              admin_hostname: 'admin'
       when: cluster_env is undefined

     - name: hostvars
       #ansible.builtin.debug:
       ansible.builtin.set_fact:
          admin_hostname: "{{ item }}"
       when: ( hostvars[item].cluster_group_name == cluster_env )
       loop: "{{ groups['admin'] }}"
       run_once: true

     - name: Print the cluster_env group inventory list
       ansible.builtin.debug:
             msg: "{{ groups[cluster_env] }}"
       run_once: true

- hosts: "{{ hostvars['localhost'].admin_hostname }}"
  become: True
  gather_facts: true
  # serial: 1
  tasks:
      - name: Print ansible-command to deploy SSH keys on "{{ inventory_hostname }}"
        ansible.builtin.debug:
                msg: "ansible-playbook -i {{ groups[hostvars[inventory_hostname].cluster_group_name] | join(',') }} cephadm-distribute-ssh-key.yml -e cephadm_ssh_user={{ cepadm_ssh_user }} -e admin_node=node2ceph5 -vv"
        #run_once: true
        delegate_to: localhost

      - name: Print Hostname where to perform the orch host add command
        ansible.builtin.debug:
            msg: "{{ inventory_hostname }}"
        #delegate_to: inventory
        #run_once: true
